spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: disk-service
          uri: lb://disk-service
          predicates:
            - Path=/api/disks/**

server:
  port: ${SERVER_PORT:8080}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${OTLP_ENDPOINT:http://localhost:8200/v1/traces}
